name: 'dbt_sqlserver_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_airflow_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_sqlserver_project:
    staging:
      +tags: ['stg']
      +materialized: view
      +schema: "{{ target.schema }}_STG"

    marts:
      +tags: ['marts']
      +materialized: table
      +schema: "{{ target.schema }}_MARTS"

    intermediate:
      +tags: ['int']
      +materialized: table
      +schema: "{{ target.schema }}_INT"