version: 2

models:
  - name: stg_sales_orders
    description: Staging model combining sales order headers and details
    columns:
      - name: sales_order_id
        description: Primary key for sales orders
        tests:
          - not_null
      - name: order_detail_id
        description: Primary key for sales order details
        tests:
          - not_null
      - name: order_date
        description: Date when the order was placed
      - name: due_date
        description: Date when the order is due
      - name: ship_date
        description: Date when the order was shipped
      - name: status
        description: Current status of the order
      - name: online_order_flag
        description: Flag indicating if the order was placed online
      - name: sales_order_number
        description: Unique sales order number
      - name: purchase_order_number
        description: Customer purchase order number
      - name: customer_id
        description: Foreign key reference to customer
      - name: sales_person_id
        description: ID of the sales person
      - name: territory_id
        description: Sales territory ID
      - name: product_id
        description: Foreign key reference to product
      - name: order_qty
        description: Quantity ordered
      - name: unit_price
        description: Unit price of the product
      - name: unit_price_discount
        description: Discount amount
      - name: line_total
        description: Total amount for this line item
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_order_id
            - order_detail_id 