dbt_airflow_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('DB_SERVER') }}"
      port: 1433
      database: AdventureWorksLT
      schema: "{{ env_var('DB_SCHEMA') }}"
      authentication: ActiveDirectoryMsi
      client_id: 2eab523c-7a3e-4816-a9b0-86b662fb20e9
      windows_login: False
      encrypt: False
      trust_cert: True
      threads: 4  # Number of concurrent operations
      timeout_seconds: 300  # Query timeout in seconds
      retries: 3  # Number of retries for failed operations
      keepalives_idle: 0  # Disable keepalive to prevent connection issues
      application_name: dbt_airflow_project  # Identify the application in SQL Server
      retry_on_error: True  # Enable automatic retries on transient errors 
